### ISSUE TITLE
Tiefsee3 vs 4 beta15 (放大后，畫質不一）

### ISSUE THREAD

**Issue by n-buna404** [hbl917070/Tiefsee4#1]
剛剛試了下Tiefsee4beta15， 放大超過100%后會明顯地糊掉。 同樣的圖片在tiefsee3 沒那麽明顯。是rendering engine 不同的問題嗎？
[https://slow.pics/c/b6bkz4tL](url)
Tiefsee4 設定；縮放：銳利，dpi: auto
Tiefsee3 有關設定；高品質成像：模式3

**Comment by hbl917070** [comment]
Tiefsee 3 的圖片縮放一律使用「平滑」，沒有提供修改縮放模式的功能，
只要把 Tiefsee 4 的「圖片縮放模式」改成「平滑」，就會接近Tiefsee 3的效果了。
我看其他圖片檢視軟體比較常用的策略是「僅放大時銳利」，
圖片大於100%還用「平滑」，其實就是要電腦去猜測那些本來不存在的像素點可能是什麼顏色，也許這會讓圖片看起來更好看，但這並不是圖片真實的樣子。

另外有一點，
Tiefsee 4的縮放是即時處理，如果用縮放品質最好的算法，將會導致程式嚴重卡頓，
而Tiefsee 3則是用品質最高的縮放算法，只要開啟開啟稍微大一點的圖片，縮放或移動圖片後，可能要等個幾秒才能算出清晰的圖片，雖然計算圖片是放在背景執行不會導致程式卡頓，但很多人反應「畫面一段時間才會刷新很煩躁」，所以沒有沿用這項設計。

**Comment by n-buna404** [comment]
> Tiefsee 3 的圖片縮放一律使用「平滑」，沒有提供修改縮放模式的功能， 只要把 Tiefsee 4 的「圖片縮放模式」改成「平滑」，就會接近Tiefsee 3的效果了。
 我看其他圖片檢視軟體比較常用的策略是「僅放大時銳利」， 圖片大於100%還用「平滑」，其實就是要電腦去猜測那些本來不存在的像素點可能是什麼顏色，也許這會讓圖片看起來更好看，但這並不是圖片真實的樣子。
> 
> 另外有一點， Tiefsee 4的縮放是即時處理，如果用縮放品質最好的算法，將會導致程式嚴重卡頓， 而Tiefsee 3則是用品質最高的縮放算法，只要開啟開啟稍微大一點的圖片，縮放或移動圖片後，可能要等個幾秒才能算出清晰的圖片，雖然計算圖片是放在背景執行不會導致程式卡頓，但很多人反應「畫面一段時間才會刷新很煩躁」，所以沒有沿用這項設計。

明白了是user preferences，好看的縮放（較吃性能）vs真實的圖案。這個放大是用upscale algorithm 如 lanczos, spline64 之類的嗎？
的確別的軟體如imageglass也是偏向後者。我找了這麽多大概只有tiefsee3 和 nomacs 是前者。
感謝解惑。

**Comment by hbl917070** [comment]
我用來縮放圖片的是JavaScript的[createImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap)，品質設定成 medium，
這個API並非所有瀏覽器都支援，edge瀏覽器具體怎麼實作這個功能的我就沒有深入研究了。
雖然也是有找到那種以js直接實現圖片縮放的算法，但是計算時間實在太長
[http://nodeca.github.io/pica/demo/](http://nodeca.github.io/pica/demo/)

**Comment by n-buna404** [comment]
> 我用來縮放圖片的是JavaScript的[createImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap)，品質設定成 medium， 這個API並非所有瀏覽器都支援，edge瀏覽器具體怎麼實作這個功能的我就沒有深入研究了。 雖然也是有找到那種以js直接實現圖片縮放的算法，但是計算時間實在太長 http://nodeca.github.io/pica/demo/


我也只是個外行人。不知道這個會不會有幫助
[https://github.com/thekevinscott/UpscalerJS](url)

**Comment by hbl917070** [comment]
這個或許能得到很好的圖片品質，但是運行成本太高
用神經網路來縮放圖片的話，就算是有獨立顯卡的電腦，一張圖片的處理時間也會超過10秒

**Comment by n-buna404** [comment]
我找了一個應該沒那麽吃效能的
[https://github.com/viliusle/Hermite-resize](url)

**Comment by hbl917070** [comment]
我有空再測試看看吧
不過理論上這種用js實現的算法都不可能比瀏覽器原生的createImageBitmap還要快
感覺比較有希望能顯著提升效能或品質的就 WebAssembly 或 webGL
畢竟createImageBitmap已經相當於直接用顯示卡來計算影像，用js去把圖片的每一個像素點都跑一輪的做法自然是不可能快的起來

**Comment by hbl917070** [comment]
剛剛實際把hermite.js下來下來測試
用4480*6720的圖片下去跑，就算是用16核心下去跑，縮放一次的成本也是大於1秒

**Comment by n-buna404** [comment]
只是好奇，同樣的圖片createImageBitmap要多久？
因爲http://nodeca.github.io/pica/demo/ 我在edge測，有createImageBitmap更沒有效能超太多了。

**Comment by hbl917070** [comment]
我的顯示卡是3060
同樣為那張4480*6720的圖片，用createImageBitmap縮放一次耗時 0.001秒~0.011秒

**Comment by n-buna404** [comment]
createImagebitmap 1-11ms 很快
如果套用https://github.com/nodeca/pica 但是强制用createImageBitmap而不是pure js不知道可不可行

**Comment by hbl917070** [comment]
pica的品質能好是因為每次都只縮放一點點，連續進行數次逐步縮放到目標大小
但圖片檢視軟體不能每次縮放都做這種大量運算，已經縮放過的資料要存在暫存裡面避免重複運算。
其實就算不在乎品質單純只用createImageBitmap也不是完美的方案，對於沒有獨立顯示卡或是GPU當下已經處於高負荷的電腦，createImageBitmap的速度會非常慢。
這方面還要花時間優化跟測試

**Comment by n-buna404** [comment]
好的明白。十分感謝你花時間出來解答。

**Comment by n-buna404** [comment]
感謝作者的優化。tiefsee4 beta17 的縮放畫已經堪比tiefsee3。我十分期待正式版的發佈。
