### ISSUE TITLE
.avif文件無法正確預覽

### ISSUE THREAD

**Issue by jushi-xianyu** [hbl917070/Tiefsee4#10]
![image](https://github.com/hbl917070/Tiefsee4/assets/110016861/c06fbea9-4499-49a2-99df-5bca3f094bdb) ![image](https://github.com/hbl917070/Tiefsee4/assets/110016861/9a228697-051b-49c6-990a-c6635bde3467)
![image](https://github.com/hbl917070/Tiefsee4/assets/110016861/eab7cb21-141b-4c0f-9c55-caca7a0f2332)
如圖所示  在tiefsee4.1.1的版本中無法預覽.avif圖片檔案
在explorer裡面也無法預覽圖片 (已經設置成.avif的預設開啟程式了)
前幾個版本中就有遇到了 但是現在才想起來要問一下
不知道如何解決或是說未來可以新增該功能? 
雖然說不是特別必要的功能 但整個資料夾的圖片裡面目前只有.avif文件無法預覽總覺得有點違和

**Comment by hbl917070** [comment]
Tiefsee 目前沒有讓檔案總管顯示預覽圖的功能

試試看裝這個
https://www.microsoft.com/store/productId/9MVZQVXJBQ9V

**Comment by jushi-xianyu** [comment]
![image](https://github.com/hbl917070/Tiefsee4/assets/110016861/f1aabfea-5848-4319-90a3-c6b7df53f47b)
![image](https://github.com/hbl917070/Tiefsee4/assets/110016861/0f3db379-fda9-4ba5-8996-c7528ee73c92)
![image](https://github.com/hbl917070/Tiefsee4/assets/110016861/bb8c6d83-7954-4560-a86e-a475f3749799)
已經安裝AV1擴展了 依舊無法正確預覽
所以正確顯示出預覽圖算是explorer的特性(?   並不是tiefsee的問題
可以這樣理解? 非相關專業不太清楚(´・ω・`)

**Comment by hbl917070** [comment]
是的，Tiefsee 目前沒有處理檔案總管預覽圖的功能
需要這功能的話需要用其他程式來實現

我這邊用win11測試，裝完那個AV1的擴充，然後重開機就可以顯示預覽圖了
