### ISSUE TITLE
info 分析錯誤

### ISSUE THREAD

**Issue by bluelovers** [hbl917070/Tiefsee4#12]
![image](https://github.com/hbl917070/Tiefsee4/assets/167966/9379bf1e-acd7-4b85-b026-07639201a50e)

```
Steps: 20
Sampler: DPM++ 2M Karras
CFG scale: 7
Seed: 1069421881  
Size: 512x768
Model hash: ec9c3259dc
Model: cetusMix_whalefall
ADetailer model: face_yolov8n.pt
ADetailer prompt: "(perfect detailed face, perfect detailed eyes, beautiful detailed eyes, beautiful detailed face, highly detailed face and eye), {prompt}"
ADetailer confidence: 0.3
ADetailer dilate/erode: 32
ADetailer mask blur: 4
ADetailer denoising strength: 0.4
ADetailer inpaint only masked: True
ADetailer inpaint padding: 32
ADetailer model 2nd: face_yolov8n.pt
ADetailer prompt 2nd: "(perfect detailed face, perfect detailed eyes, beautiful detailed eyes, beautiful detailed face, highly detailed face and eye), {prompt}"
ADetailer confidence 2nd: 0.3
ADetailer dilate/erode 2nd: 32
ADetailer mask blur 2nd: 4
ADetailer denoising strength 2nd: 0.4
ADetailer inpaint only masked 2nd: True
ADetailer inpaint padding 2nd: 32
ADetailer version: 23.7.11
Lora hashes: "ConceptAlraunePlantGirl_v2: 16c412356cdf"
TI hashes: "EasyNegative: c74b4e810b03"
Version: mark/20230731-12-gc10633f9
```

**Comment by hbl917070** [comment]
這圖片是用什麼程式產生的，方便提供一些可以測試的圖片樣本嗎

**Comment by bluelovers** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui

+ ADetailer

![image](https://github.com/hbl917070/Tiefsee4/assets/167966/30a5505f-08d6-4760-9216-4070c84e75e9)

然後隨便產生一個有臉的圖

不過我是覺得不需要特地去生圖片來測試
因該就只是遇到了 `" , { }` 這些字元導致沒有完整分析
或者你在判斷 info 的時候 有擷取長度
所以才會導致沒有完整分析

![tmpwhamhknt](https://github.com/hbl917070/Tiefsee4/assets/167966/6ee85915-1fb5-4914-916e-7f4c230cae85)

**Comment by hbl917070** [comment]
https://github.com/hbl917070/Tiefsee4/commit/f8e85452dfa49c377809585d39e75f4b71188303 已嘗試修復這個錯誤

可以試試看 4.1.2.1版
https://github.com/hbl917070/aeropic/tree/master/download/nightly
