### ISSUE TITLE
长按空格 查看 一按就 报错这个代码

### ISSUE THREAD

**Issue by lhj5426** [hbl917070/Tiefsee4#17]
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: ...rtableMode\Plugin\QuickLook\QuickLook.Native64.dll
File: C:\projects\quicklook\QuickLook.Native\Q...\rapidxml.hpp
Line: 1388

Expression: text

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
中止(A)   重试(R)   忽略(I)   
---------------------------
![image](https://github.com/hbl917070/Tiefsee4/assets/30548000/f803e40a-1e8e-4e14-8f7a-ad91e9f1253f)
GPT 好像说了什么 又好像没说 什么 看不懂

忘记说了 
我是在 
![image](https://github.com/hbl917070/Tiefsee4/assets/30548000/490893e7-2c1e-4c03-858c-f7c83914cab3)
这个资源管理器里长按 空格 报错的
系统那个自带的垃圾资源管理了是没问题的 

还有就是很多年了 一直在用您开发的
![image](https://github.com/hbl917070/Tiefsee4/assets/30548000/87d81544-4ab2-4aef-b188-f3f39dde7933)
这个东西作为 屏幕l录制的显示信息
能不能请您更新一下 支持下自定义字体 因为网上找不到第二个 这么好用的桌面文字显示工具
就是不能更改字体有点 难受

**Comment by hbl917070** [comment]
已經嘗試修復在 Directory Opus 下無法使用的問題
重新安裝 QuickLook 擴充套件 應該就行了 ，試試看
https://hbl917070.github.io/aeropic/zh-TW/plugin.html

即時字幕我這幾天整理下再上 GitHub

**Comment by lhj5426** [comment]
> 已經嘗試修復在 Directory Opus 下無法使用的問題 重新安裝 QuickLook 擴充套件 應該就行了 ，試試看 https://hbl917070.github.io/aeropic/zh-TW/plugin.html
> 
> 即時字幕我這幾天整理下再上 GitHub

非常感谢 重新 安装之后 在DO 里已经可以正常长按显示图片了

**Comment by lhj5426** [comment]
期待  即時字幕 的更新哈哈 这个 快10年的小工具了

**Comment by hbl917070** [comment]
即時字幕 已經上傳了
https://github.com/hbl917070/InstantSubtitle

**Comment by lhj5426** [comment]
> 即時字幕 已經上傳了 https://github.com/hbl917070/InstantSubtitle

![image](https://github.com/hbl917070/Tiefsee4/assets/30548000/e5d2d9a0-3eb6-4eae-a539-b91106bedae9)
感谢您 开发者 大佬
这么多年 终于盼到 可以更换字体了
简直像是做梦一样 真的非常感谢您！！！！！
