### ISSUE TITLE
「左鍵雙擊」如果設成「縮放至適合視窗or圖片原始大小」功能似乎異常

### ISSUE THREAD

**Issue by d13650martin** [hbl917070/Tiefsee4#18]
作者你好～

如圖所示，
在設定裡面有個「滑鼠」→「滑鼠按鍵」，
第一項「左鍵雙擊」這個自訂功能，
當我把它設定成「縮放至適合視窗or圖片原始大小」時，
在圖片是原始大小的狀態下雙擊左鍵，
圖片會縮至適合視窗的大小，
但這時候再次雙擊左鍵，
圖片卻沒辦法切回原始的大小，

也就是說沒辦法透過雙擊左鍵讓圖片在適合視窗與原始大小之間來回切換，
因為我之前用過的看圖軟體有這種功能，
已經習慣了這樣的操作方式，

請問這是正常設定嗎？
還是說這目前是BUG？

假如是BUG的話希望能盡快修復，
感謝～

![20230906_062243'](https://github.com/hbl917070/Tiefsee4/assets/144181128/b41dadb9-c194-4545-89a3-fddc1561daf7)

**Comment by hbl917070** [comment]
這個功能是「將圖片縮放至適合視窗，不過如果圖片原始大小小於視窗大小，則顯示圖片原始大小」

你說的應該是「原始大小 與 適合視窗 之間進行切換」，目前沒有這個功能
這確實是很常見的操作，我試試看能不能新增這個功能

**Comment by d13650martin** [comment]
> 這個功能是「將圖片縮放至適合視窗，不過如果圖片原始大小小於視窗大小，則顯示圖片原始大小」
> 
> 你說的應該是「原始大小 與 適合視窗 之間進行切換」，目前沒有這個功能 這確實是很常見的操作，我試試看能不能新增這個功能

**Comment by d13650martin** [comment]
> 這個功能是「將圖片縮放至適合視窗，不過如果圖片原始大小小於視窗大小，則顯示圖片原始大小」
> 
> 你說的應該是「原始大小 與 適合視窗 之間進行切換」，目前沒有這個功能 這確實是很常見的操作，我試試看能不能新增這個功能

**Comment by hbl917070** [comment]
已經提交了「縮放至適合視窗/圖片原始大小 切換」的程式碼，
可以在最新的 Nightly版 測試這項功能
https://github.com/hbl917070/Tiefsee4/releases

![image](https://github.com/hbl917070/Tiefsee4/assets/12185698/02dff634-72f6-43a1-b1e6-a04ee38cadbe)

**Comment by d13650martin** [comment]
辛苦了
真是太感謝了！

**Comment by d13650martin** [comment]
想請問一下這功能以後會上架到商店正式版嗎？
