### ISSUE TITLE
可否在大量浏览模式下对当前浏览的图片进行实时刷新

### ISSUE THREAD

**Issue by lhj5426** [hbl917070/Tiefsee4#19]
这个需求是怎么来的呢
如图大佬看到的这样
我在用机器翻译软件 翻译看漫画 但是这个软件的看漫画功能做的用起来很别扭
所以我就选择用大佬您开发的软件来进行阅读
但是机翻嘛  识别和翻译的时候难免有漏缺的地方这时候就要
![image](https://github.com/hbl917070/Tiefsee4/assets/30548000/d3bccf04-a2ba-4387-9af0-befc722224ef)

![image](https://github.com/hbl917070/Tiefsee4/assets/30548000/26f3ef67-b060-4961-8438-9cbb46ae1032)
切换到漫画翻译软件这边
然后 弄完之后再切换到您的看图软件这边接着往下看
这个时候 翻译软件已经把图片刷新了
但是 大佬您软件这边没有 实时刷新 或者说 没有对单独页面的刷新功能
现在一按F5刷新 就是页面回到
![image](https://github.com/hbl917070/Tiefsee4/assets/30548000/1363afc5-6a25-47d7-8f28-0425a6db8210)
最开始的模式 并且回到了第一页
所以能不能增加一个实时刷新功能就像  Honeyview 这个软件那样
就算开着相同的页面 其他软件修过刷新了这个图片 在这个软件打开的图片也会跟着实时刷新
如视频这样

https://github.com/hbl917070/Tiefsee4/assets/30548000/bb03ef2b-461c-4211-a78a-e85dfd3cb897

不知道您是否看到 明白 
不知可否增加这个功能
还有可否增加 一个记录模式和缩放的功能
![image](https://github.com/hbl917070/Tiefsee4/assets/30548000/4dabacc9-746c-4d48-91c1-7168fb9d9979)
比如我打开的是 大量浏览模式 80%缩放
然后关闭了软件
下次启动的时候 还是 在大量浏览模式 和80%缩放 这个模式下

**Comment by hbl917070** [comment]
大量瀏覽模式的所有設定都是會記錄的，不過只有關閉 Tiefsee 的時候才會記錄設定
有想過改善這個儲存機制，但目前還沒有明確的方案
也許有人就是有不同視窗使用不同設定值的需求，如果處理成同步所有視窗的設定值，某些情況下反而是一種麻煩

4.1.2 版有加入檔案變化的偵測了，檔案被修改後，Tiefsee 會顯示一個可以刷新的按鈕
![GIF 2023-9-8 下午 08-36-07](https://github.com/hbl917070/Tiefsee4/assets/12185698/c36db8e3-b4a6-4066-8116-07d29f632107)

F5 是觸發瀏覽器的刷新，而不是 Tiefsee 的重新載入圖片，是我為了 debug 才沒有封鎖這個功能
本來我是想說等到自訂快速鍵的功能上線再一併處理
如果你覺得 4.1.2 版的自動偵測檔案變化依然不能解決你的問題，我這邊也是可以優先處理，畢竟瀏覽器的刷新並不是 Tiefsee 的正常操作流程，用了會導致一些問題，例如設定值跑掉

**Comment by hbl917070** [comment]
商店版只能更新成最新，不能降板
遍攜版的話，這裡可以下載到所有歷史版本，也有最新的開發預覽版
https://github.com/hbl917070/Tiefsee4/releases

沒有設計「預設開啟就進入大量瀏覽模式」的功能，是因為沒有辦法根據開啟的圖片自動定位到那張圖片的位置
例如有個資料夾內有1000張圖片，但不管使用者開啟第500張圖片還是第800張圖片
進入大量瀏覽模式都是從第1張圖片開始
那些有辦法自動定位的程式，圖片都是處理成固定的正方形，所以才有辦法根據圖片數量來計算要捲動到什麼位置
但 Tiefsee 的大量瀏覽模式裡面的圖片並不是固定的正方形，載入圖片需要時間，等到當前頁所有圖片都載入完畢才能定位，這可能已經是3秒甚至是10秒以後的事情

**Comment by lhj5426** [comment]
> 商店版只能更新成最新，不能降板 遍攜版的話，這裡可以下載到所有歷史版本，也有最新的開發預覽版 https://github.com/hbl917070/Tiefsee4/releases
> 
> 沒有設計「預設開啟就進入大量瀏覽模式」的功能，是因為沒有辦法根據開啟的圖片自動定位到那張圖片的位置 例如有個資料夾內有1000張圖片，但不管使用者開啟第500張圖片還是第800張圖片 進入大量瀏覽模式都是從第1張圖片開始 那些有辦法自動定位的程式，圖片都是處理成固定的正方形，所以才有辦法根據圖片數量來計算要捲動到什麼位置 但 Tiefsee 的大量瀏覽模式裡面的圖片並不是固定的正方形，載入圖片需要時間，等到當前頁所有圖片都載入完畢才能定位，這可能已經是3秒甚至是10秒以後的事情

我在提交这个问题的时候 我用的版本是 最新 Nightly 版 并没有发现可以自动刷新这个功能 我才提交的这个问题
我刚才下载了4.13  也没有发现 请问 侦测刷新的功能是在哪里开启呢？

**Comment by hbl917070** [comment]
預設就是開啟的，目前也沒有設計可以關閉的選項
檢查看看是不是右下角圖示那邊沒有完全結束 Tiefsee
![image](https://github.com/hbl917070/Tiefsee4/assets/12185698/e93c667d-a9c8-4051-91a6-352047717853)

**Comment by lhj5426** [comment]
> 預設就是開啟的，目前也沒有設計可以關閉的選項 檢查看看是不是右下角圖示那邊沒有完全結束 Tiefsee ![image](https://user-images.githubusercontent.com/12185698/266643249-e93c667d-a9c8-4051-91a6-352047717853.png)
![image](https://github.com/hbl917070/Tiefsee4/assets/30548000/1e1e5804-5aba-49f7-a754-e23713f4d0e9)
 我把全部删掉 重新 下载 解压之后 默认就有了 可能之前设置哪里给改掉了 嘛 自身就有这个功能 浪费了一次issues 哈哈 
 非常感谢
