### ISSUE TITLE
4.0.0-beta.23 圖片長寬資料有誤

### ISSUE THREAD

**Issue by dmnohftaw** [hbl917070/Tiefsee4#2]
最近載了一張JPG下來 發現長寬尺寸有誤
圖片被縮得很小
詳細資料視窗是正確的
https://www.mediafire.com/view/jbhwb6zcvdlnhxy/ganyu.jpg

**Comment by hbl917070** [comment]
確實有此問題
beta.24 會發佈此修正
https://github.com/hbl917070/Tiefsee4/commit/244886886098d4d471704afa42d9e688d2e7b2ce

**Comment by hbl917070** [comment]
已發佈beta.24，試試看問題是否得到修復了

**Comment by dmnohftaw** [comment]
> 已發佈beta.24，試試看問題是否得到修復了

現在正常了
