### ISSUE TITLE
希望向舊版一樣有大量瀏覽模式的快捷鍵

### ISSUE THREAD

**Issue by kakeru168** [hbl917070/Tiefsee4#21]
以前使用舊版習慣設在側鍵開啟  新版沒了有點不習慣

然後大量瀏覽模式下對圖片點左鍵會回到一般瀏覽    略有點不便

**Comment by hbl917070** [comment]
我不確定你說的「大量瀏覽模式的快捷鍵」是指什麼

至於在大量瀏覽模式裡面點擊圖片後回到一般瀏覽，這部分是真的沒辦法
跳出一個子視窗確實更直覺
但使用者在大量瀏覽模式點選某一張圖片後，可能會需要要對做一些操作
像是旋轉圖片、搜圖、刪除圖片、查看詳細資料面板 等...
表示這個顯示圖片的子視窗幾乎需要實作一般瀏覽的所有功能
既然功能跟一般瀏覽沒有區別，那像是子視窗就只是讓四周圍多出沒有用途的邊框
像這樣
![2023-10-05 20-16-08](https://github.com/hbl917070/Tiefsee4/assets/12185698/1f53ead0-ca88-425e-9472-b6a9a9f1c034)

我認為需要解決的問題是，如何更快速的從一般瀏覽返回大量瀏覽模式
下一版(4.1.4版) 可以在滑鼠那邊設定按下滑鼠滾輪鍵或側鍵來回到大量瀏覽模式
![image](https://github.com/hbl917070/Tiefsee4/assets/12185698/90f8919b-9a1d-49d1-9318-9fa884fe1d7b)

**Comment by kakeru168** [comment]
在舊版大量瀏覽使用B做快捷鍵  我通常放在G502的瞄準鍵上  但這次新版沒有滾輪以外的鍵可以設定

**Comment by hbl917070** [comment]
新版的一樣是快速鍵「B」開啟大量瀏覽模式呀
是不是因為中文輸入法導致快速鍵無法觸發？

**Comment by kakeru168** [comment]
哦!原來快捷鍵跟以前一樣   沒看到說明我以為新版換掉快捷鍵了
