### ISSUE TITLE
希望支持webp格式

### ISSUE THREAD

**Issue by xepo123** [hbl917070/Tiefsee4#23]
打开webp的韩漫，显示error

**Comment by hbl917070** [comment]
正常情況下是可以開啓webp的
不過目前缺少檢測webp副檔名的機制，所以如果不是webp的檔案卻使用webp當副檔名就會出錯（例如把一張png圖片的副檔名改成webp）

如果你説的情況並非副檔名錯誤導致，可以提供會引發錯誤的圖片，我這邊測試看看是什麽問題

**Comment by xepo123** [comment]
重命名jpg,可以看。
没问题了

**Comment by hbl917070** [comment]
4.1.5 已修復此問題
就算副檔名錯誤可以正常開啟圖片
