### ISSUE TITLE
Tiefsee 中的兩個 Data 資料夾在大小寫不敏感的作業系統中存在警告

### ISSUE THREAD

**Issue by charles7668** [hbl917070/Tiefsee4#26]
從提交上來看 小寫的 data 應該是已經棄用的 , 但還保留在 git repo 上

![圖片](https://github.com/hbl917070/Tiefsee4/assets/30816317/900dc20c-c024-4873-a38d-593f64c94d20)
![圖片](https://github.com/hbl917070/Tiefsee4/assets/30816317/439e2439-61f0-4087-a86a-179fadf3e574)

**Comment by hbl917070** [comment]
謝謝。
這確實是沒有清理乾淨的舊資料
