### ISSUE TITLE
DDS檔會錯誤

### ISSUE THREAD

**Issue by lpin000031** [hbl917070/Tiefsee4#28]
只要是DDS格式的都打不開，3.0.8時還可以，換到4.1.6就不行了

**Comment by lpin000031** [comment]
這個版本可以直接看到了，不過我在檔案總管裡還是沒辦法看到縮圖

**Comment by hbl917070** [comment]
是的，Tiefsee 沒有覆寫檔案總管縮圖的功能

**Comment by lpin000031** [comment]
![圖片](https://github.com/hbl917070/Tiefsee4/assets/40206295/58afd676-7617-4fa4-93be-70cee2c13b5a)
旁邊預覽還是看不到，這跟檔案總管有關係嗎

**Comment by hbl917070** [comment]
目前 Tiefsee 的檔案預覽面板，是直接抓檔案總管的圖示
其實有很多圖片是沒有內嵌縮圖的，沒有縮圖的檔案類型就要完整讀取整張圖片，才能繪製預覽圖
假設資料夾內有10張300m的bmp圖片，如果實際去繪製縮圖，那麼只要開其中一個檔案，就會同時把這10張300m的圖片載入到記憶體裡面處理
所以才會暫時用檔案總管的圖示，而非實際去繪製預覽圖

**Comment by lpin000031** [comment]
那我懂了，剩下的問題應該是那個DDS檔本身的問題
