### ISSUE TITLE
QuickLook 這個功能 在 Q-Dir 如何使用

### ISSUE THREAD

**Issue by at3166** [hbl917070/Tiefsee4#29]
QuickLook 這個功能 我在[ Q-Dir](https://www.softwareok.com/?seite=Freeware/Q-Dir) 不能使用，
請問有辦法關聯嗎？
謝謝。

**Comment by hbl917070** [comment]
QuickLook 的功能是使用這個專案的 DLL 來實現的
https://github.com/QL-Win/QuickLook

如果上游專案本身就無法實現這個功能，老實說我這邊也沒辦法處理

**Comment by at3166** [comment]
好的，感謝回覆。
