### ISSUE TITLE
支援 portable 模式

### ISSUE THREAD

**Issue by bluelovers** [hbl917070/Tiefsee4#3]
目前雖然是 下載解壓縮之後 就能用
但資料設定的部分希望能允許支援 儲存在 與程式同資料夾下

也可以參考類似 如果資料夾下存在 `portable_mode` 這個檔案
就會以 portable 模式來執行

**Comment by hbl917070** [comment]
很實用的設計概念
目前 Tiefsee4 的相對路徑是統一用全域變數來管理，理論上只要改個全域變數，就能實現這個portable的功能

不過在這之前，我可能要先處理「安裝」的功能
可能是直接上架到微軟的商店，或是用一些工具打包成安裝檔
不確定這會不會有什麼限制，導致需要調整專案架構

**Comment by hbl917070** [comment]
已於 4.1.0版 加入此功能
免安裝版的 TIefsee，在程式旁邊新增 `portableMode` 資料夾後，資料會改成儲存在這個資料夾內
