### ISSUE TITLE
圖檔與文件是否可以同時預覽？

### ISSUE THREAD

**Issue by at3166** [hbl917070/Tiefsee4#30]
請問，
在同一個資料夾底下 有 圖檔(*.jpg,*.png) 與 文件(*.txt,*.sql,*.md) 是否可以同時預覽？
謝謝。

**Comment by hbl917070** [comment]
目前沒有這個功能
不過可以選擇多個檔案拖進 Tiefsee 裡面來進行開啟
如果選擇的檔案同時包含圖片與文件，那麼就會同時出現在檔案預覽面板
