### ISSUE TITLE
開啟巨大圖片時cpu佔用超高

### ISSUE THREAD

**Issue by jimgo514** [hbl917070/Tiefsee4#34]
我有一張169776*2200的圖，
用Tiefsee開了後cpu直接爆滿，電腦卡爛，
用win10內建的相片是可以開這張圖的，
希望若開不了這麼大的圖片可以跳錯誤，而不是卡住整台電腦。

圖：[2024-03-28_16.18.48-ae2.zip](https://github.com/hbl917070/Tiefsee4/files/14786525/2024-03-28_16.18.48-ae2.zip)
佔用情況：
![螢幕擷取畫面 (267)](https://github.com/hbl917070/Tiefsee4/assets/64835962/9a50a3de-862d-464f-ba0a-0317910c76c3)
![螢幕擷取畫面 (266)](https://github.com/hbl917070/Tiefsee4/assets/64835962/f08955ff-9b81-45eb-bc56-3eb3638224ec)
版本4.1.3.0（商店）
我也試了github上的4.2.1，一樣卡

**Comment by hbl917070** [comment]
已提交修復的程式碼 https://github.com/hbl917070/Tiefsee4/commit/30c274f18f0b59dcdd10ca63649e8f44a00d768a

想要測試看看的話，可以下載 Nightly 版
https://github.com/hbl917070/Tiefsee4/releases

不過目前這只能算是應急方案，因為 `<canvas>` 的長寬上限是 65535
為了讓圖片可以順利顯示
當 canvas 無法處理圖片時，就會切換成用 `<img>` 來顯示圖片，這個切換過程沒辦法使用非同步處理
