### ISSUE TITLE
大量瀏覽模式有部分資料夾找不到

### ISSUE THREAD

**Issue by akalivaty** [hbl917070/Tiefsee4#35]
1. 如影片，DLC++++(4個+)和DLC+++++(5個+)在大量瀏覽中找不到
2. 單獨點DLC++++(4個+)和DLC+++++(5個+)裡的圖片可進入大量瀏覽模式，一旦切換資料夾就只能看到DLC++++++(6個+)
3. 拖曳DLC++++(4個+)和DLC+++++(5個+)資料夾到大量瀏覽模式也看不到

https://github.com/hbl917070/Tiefsee4/assets/73537279/35668bb8-9a6e-4e37-82d1-27442495b0f6

**Comment by hbl917070** [comment]
已嘗試修正這個 BUG

想要先測試看看的話可以下載 Nightly 版
https://github.com/hbl917070/Tiefsee4/releases
