### ISSUE TITLE
ERROR message, no image displayed

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [hbl917070/Tiefsee4#38]
Continuing the message from CivitAI (https://civitai.com/models/197996?dialog=commentThread&commentId=388093&highlight=414004)

I tried installing .NET 8.0, and it didn't fix it unfortunately. 
I tried both the MS store and portable version.
I tried it on 2 computers, both Windows 11.

Both give the same ERROR message as shown in the screenshot below.

![image](https://github.com/hbl917070/Tiefsee4/assets/60541708/bbc84650-cb8c-47b8-acb1-0b4b00bedb3b)

This used to work fine on the same machine before a format. I even tried with the same files (exactly the same portable version as I still have access to my old C:\ drive), and it's not working. I was using version 1.60, but this is now showing the same error for me.

Is there anything I can do to further debug the actual error happening to me?

**Comment by hbl917070** [comment]
After launching Tiefsee, press `F12` on your keyboard to open devTools, 
then switch to the `Console` and `Network` tabs, 
after that, try to load some images that will generate errors, and see if there are any red error messages.

![image](https://github.com/hbl917070/Tiefsee4/assets/12185698/5ecd80d8-6bd3-4b02-bc22-02a8ca85a41d)

**Comment by MNeMoNiCuZ** [comment]
Console:
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
vipsResize:1 
        
        
        GET http://127.0.0.1:4877/api/img/vipsResize?path=C%3A%5CAI%5Cstable-diffusion-webui-forge%5Coutput%5Ctxt2img-images%5C2024-05-13%5C2024-05-13%20-%2001.32.33.png&scale=0.8&type=png&LastWriteTimeUtc=1715556754152 500 (Internal Server Error)
127.0.0.1:4877/api/img/vipsResize?path=C%3A%5CAI%5Cstable-diffusion-webui-forge%5Coutput%5Ctxt2img-images%5C2024-05-13%5C2024-05-13%20-%2001.33.01.png&scale=0.8&type=png&LastWriteTimeUtc=1715556781699:1 
        
        
        GET http://127.0.0.1:4877/api/img/vipsResize?path=C%3A%5CAI%5Cstable-diffusion-webui-forge%5Coutput%5Ctxt2img-images%5C2024-05-13%5C2024-05-13%20-%2001.33.01.png&scale=0.8&type=png&LastWriteTimeUtc=1715556781699 500 (Internal Server Error)
```

Network:
```
Request URL:
http://127.0.0.1:4877/api/img/vipsResize?path=C%3A%5CAI%5Cstable-diffusion-webui-forge%5Coutput%5Ctxt2img-images%5C2024-05-13%5C2024-05-13%20-%2001.33.28.png&scale=0.8&type=png&LastWriteTimeUtc=1715556809529
Request Method:
GET
Status Code:
500 Internal Server Error
Remote Address:
127.0.0.1:4877
Referrer Policy:
strict-origin-when-cross-origin
Content-Type:
text/text; charset=utf-8
Date:
Mon, 13 May 2024 10:28:49 GMT
Server:
Microsoft-HTTPAPI/2.0
Transfer-Encoding:
chunked
Accept:
image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
Accept-Encoding:
gzip, deflate, br, zstd
Accept-Language:
en-US,en;q=0.9
Connection:
keep-alive
Host:
127.0.0.1:4877
Sec-Ch-Ua:
"Chromium";v="124", "Microsoft Edge";v="124", "Not-A.Brand";v="99", "Microsoft Edge WebView2";v="124"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"Windows"
Sec-Fetch-Dest:
image
Sec-Fetch-Mode:
no-cors
Sec-Fetch-Site:
cross-site
User-Agent:
Tiefsee
```

**Comment by hbl917070** [comment]
I have adjusted the code that might be causing the problem, 
but since I can't reproduce this bug, 
I can only ask you to help me test whether this adjustment has fixed the problem.

Tiefsee Nightly Release：
https://github.com/hbl917070/Tiefsee4/releases

**Comment by MNeMoNiCuZ** [comment]
Console:
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
vipsResize:1 
        
        Failed to load resource: the server responded with a status of 500 (Internal Server Error)
vipsResize:1 
```


Network:
```
Request URL:
http://127.0.0.1:4877/api/img/vipsResize?path=C%3A%5C2024-05-11%20-%2012.53.29.png&scale=0.8&fileType=png&vipsType=vips&LastWriteTimeUtc=1715424809653
Request Method:
GET
Status Code:
500 Internal Server Error
Remote Address:
127.0.0.1:4877
Referrer Policy:
strict-origin-when-cross-origin
Content-Type:
text/text; charset=utf-8
Date:
Mon, 13 May 2024 17:49:04 GMT
Server:
Microsoft-HTTPAPI/2.0
Transfer-Encoding:
chunked
Accept:
image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
Accept-Encoding:
gzip, deflate, br, zstd
Accept-Language:
en-US,en;q=0.9
Connection:
keep-alive
Host:
127.0.0.1:4877
Sec-Ch-Ua:
"Chromium";v="124", "Microsoft Edge";v="124", "Not-A.Brand";v="99", "Microsoft Edge WebView2";v="124"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"Windows"
Sec-Fetch-Dest:
image
Sec-Fetch-Mode:
no-cors
Sec-Fetch-Site:
cross-site
User-Agent:
Tiefsee
```


There shouldn't be anything blocking it. I'm not blocking ports, and I run other servers locally just fine.
Including Tiefsee on my previous installation (same router).

**Comment by MNeMoNiCuZ** [comment]
In the `http://127.0.0.1:4877/api/img/vipsResize?path=C%3A%5C2024-05-11%20-%2012.54.02.png&scale=0.8&fileType=png&vipsType=vips&LastWriteTimeUtc=1715424842948`

The preview tab has this info:

```
System.FormatException: The input string '0.8' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Double.Parse(String s)
   at Tiefsee.WebServerController.ImgVipsResize(RequestData d)
   at Tiefsee.WebServer.<>c__DisplayClass8_0.<RouteAdd>b__0(RequestData requestData)
   at Tiefsee.WebServer.GetContextCallBack(IAsyncResult ar)
   ```

**Comment by hbl917070** [comment]
This error seems to be because the decimal point in some regions is `,` instead of `.` which leads to parsing errors. 
I have tried to fix this problem, please check if the issue still exists.
https://github.com/hbl917070/Tiefsee4/releases

**Comment by hbl917070** [comment]
The new features have been mostly developed this time. 
If the tests go well, the next version will be released in a few days.
