### ISSUE TITLE
瀏覽時，如果新增圖片就無法看見新圖片

### ISSUE THREAD

**Issue by nacl1415** [hbl917070/Tiefsee4#4]
我在瀏覽圖片，這時候SD同步產圖，但是產出來的新圖是看不見的
必須重開圖片程式才能載入新圖片
希望可以在同一個資料夾新圖片產生的時候
就自動載入程式裡
這樣就不用每次都要重新關閉打開
感謝作者

**Comment by nacl1415** [comment]
提供一個思路給大大參考
在前往下一張圖片的時候
可以檢查實體路徑的檔案名稱是否與原本相同
如果不同，則代表有新圖片產生
這時就載入新圖片

**Comment by hbl917070** [comment]
Windows有提供監控資料夾是否發生變化的功能，
更新列表的成本之所以會高，是因為需要篩選檔案跟排序檔案，
像是SD產圖的資料夾，裡面就算有幾萬張圖片也不奇怪，如果用的是以日期來排序，那麼更新一次列表的處理時間可能會超過3秒。
如果設計成自動更新列表的話，那麼SD每產一張圖，Tiefsee就會卡3秒，這將會是災難。

按上下一張圖片的時候才更新列表，確實可以解決上述的問題，
但是按下一張圖片，載入的圖片卻跟列表顯示的圖片不一樣，是一件奇怪的事情

折中方案是，偵測到資料夾有變化，就跳出一個「更新列表」的按鈕，按了才更新列表

**Comment by nacl1415** [comment]
當開啟"大量瀏覽"或"預覽功能"時
按下「更新列表」的按鈕，來刷新全局圖片列表
這個做法很合理也不會造成頻繁卡頓，同意支持

那是否有可能在不需要預覽圖時，實現正確瀏覽功能呢?
例如我自己在使用的時候，左側是沒有開啟圖片預覽列表的
那是否有機會在此模式下，實現正確讀取下一張的功能呢?

當"前往下一張圖片"時，因為沒有需要大量預覽
所以無需全面讀取，只需讀取正確的下一張圖就好

**Comment by hbl917070** [comment]
一般來說不會這樣子設計才對，我沒看過有什麼程式會因為開啟某個面板就導致運行邏輯不一樣的

我還是盡量試試看能不能實現自動更新吧，真的會有效能問題的話，就退回我說的折中方案

**Comment by nacl1415** [comment]
了解! 辛苦了!
非常感謝作者大大

或許能把"自動更新" 這功能放入選項裡
讓有需要的人自行去啟用
可說明自動更新可能會有效能問題
就讓使用者自己去決定是否開啟
當然也可以有作者大大說的自動更新按鈕放在工具列
功能都可以同時並存，讓使用者自己選擇合適的方法

**Comment by nacl1415** [comment]
太棒了! 等這個功能等了好久!
太感謝大大了!
