### ISSUE TITLE
Why does tiefsee create files in C:\Users\[USER]\Downloads\Civitai\?

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [hbl917070/Tiefsee4#41]
![image](https://github.com/hbl917070/Tiefsee4/assets/60541708/f92c8add-fe84-48c8-ad64-fb9349602c77)
It seems to create these files for me automatically. 
Is there a way to block/prevent this? I don't want a bunch of images like this being downloaded behind my back.

**Comment by hbl917070** [comment]
Simply turn off `Display Civitai Resources`.
![image](https://github.com/hbl917070/Tiefsee4/assets/12185698/be1ad52b-e07e-4ac2-8e3a-17632761b729)

**Comment by MNeMoNiCuZ** [comment]
Nice, thank you.

Nice feature, I just wish it stored it in temporary downloaded files, not in the downloads folder.

**Comment by MNeMoNiCuZ** [comment]
I get it. Similar to how the CivitAI Helper extension works in A1111.

https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper

It think it's a cool feature, but to me it's less useful and I would rather it didn't make the API calls or have any performance loss due to this information gathering. And especially not saving the files locally, that seems very creepy and obtrusive, which is why I suggested the temp-directory.

>I’m considering designing a feature that allows users to replace the preview image, but I’m still evaluating how to implement this feature.

To suggest a solution to this, why not match what A1111 does? Let the user drag/drop an image from the displayed image, or the folder list on the left side, on top of these resource thumbnails at the bottom. 

You could also let the user right-click on the resource, and choose to upload a preview, or use the selected image.

This then creates a copy of the image (maybe thumbnail sized), with the same name as the model resource thumbnail already had. And the original resource thumbnail is renamed and gets a ".preview" suffix added before the extension.

Example:
`Dreamshaper8.preview.png`

This is how A1111 handles it. It keeps the original images around if needed, and it lets the user add their own.

I created an extension that lets the user follow this standard and switch between multiple icon sets in an extension tab bar for A1111. https://github.com/MNeMoNiCuZ/sd-webui-thumbnailizer

I don't think it's relevant for Tiefsee though, but just to broaden the topic a little bit :)

**Comment by hbl917070** [comment]
I originally planned to put a ‘Change Preview Image’ option in the right-click menu of the preview image, 
However, things are not that simple, 
Some Civitai Resources have less than 3 preview images, or even no images, 
Another issue is the ‘Allow NSFW images’ feature in the settings, the enabling and disabling of this option will affect the order of the images.

Because I feel this will take quite some time to develop, I decided to improve these features in the next version.

**Comment by MNeMoNiCuZ** [comment]
Yeah, maybe it's not a very high priority. Unless you know that it has a very high engagement rate.
