### ISSUE TITLE
無法使用滑鼠滾輪切換圖片

### ISSUE THREAD

**Issue by hcaynahs** [hbl917070/Tiefsee4#42]
原本設定成用滾輪切換圖片，前幾天我更新成最新版本(4.2.1)和新的.NET之後，滾輪就無法切換圖片了
也無法從設定裡變更。好像跟滾輪有關的設定都被固定了，無法改變設定
嘗試換成更舊或更新的版本也是一樣的問題，請幫我看看

**Comment by hbl917070** [comment]
你是說這個嗎，我這邊測試是可以正常使用的
Win10、 Tiefsee 4.2.2版
![image](https://github.com/hbl917070/Tiefsee4/assets/12185698/02f0d6d4-6b4e-42f0-90fa-c1071077201e)

確定有問題的話，開啟設定視窗後，按下鍵盤的「F12」開啟 DevTools
看看裡面有沒有錯誤訊息

**Comment by hcaynahs** [comment]
我試著全部重新設定，但使用起來還是一樣
滾動>沒有反應，Ctrl+滾動>放大縮小，shift或alt>上下移動，好像無法左右移動
![123456](https://github.com/hbl917070/Tiefsee4/assets/170889146/9e53757a-6fb1-437d-b153-bcf1c6124259)

不好意思我不懂程式，不確定我應該找什麼東西
![1234567](https://github.com/hbl917070/Tiefsee4/assets/170889146/5b3f80ea-341d-428a-ab36-a3d59dd80941)

我目前也是Win10、Tiefsee 4.2.2版

**Comment by hbl917070** [comment]
所以現在設定視窗已經可以正常更改設定值了?
那試著在 Tiefsee 本體的視窗按 F12，然後輸入 `mainWindow.config.settings.mouse.scrollUp`
如果設定有正確套用，那麽就會顯示 `prevFile` ，這個就是「上一個檔案」的意思
![image](https://github.com/hbl917070/Tiefsee4/assets/12185698/41a374bf-cd2b-45ad-8013-1c47567c6447)

**Comment by hcaynahs** [comment]
抱歉沒說明清楚，一直都可以改設定，只是改了之後操作不會跟著改變
好像只有捲動類的會這樣，左鍵和滾輪鍵都可以正常設定

程式看起來是正常的 :(
![123](https://github.com/hbl917070/Tiefsee4/assets/170889146/bd016939-8ddf-49b3-b074-99fc5b7673cc)

**Comment by hbl917070** [comment]
原本使用的 Tiefsee 版本是多少
用的滑鼠是那種滾輪可以高速捲動的類型嗎
是否有觸控板(筆電鍵盤下面用來移動滑鼠的那個)

**Comment by hbl917070** [comment]
滾輪的預設值是縮放圖片，你現在用4.2.2版是可以透過滾輪來縮放圖片嗎

如果現在回去用4.1.6版，是可以正常使用滾輪來切換檔案的嗎
https://github.com/hbl917070/Tiefsee4/releases/tag/4.1.6

**Comment by hcaynahs** [comment]
直接滾動沒有反應，但是可以捲動卷軸(比如檔案預覽面板和大量瀏覽模式)，縮放圖片只能Ctrl+滾動
改成舊版也沒辦法，也有試過把NET8解安裝裝更舊的4.1.0，也是一樣的問題，好像都沒辦法改了 :(

**Comment by hbl917070** [comment]
把這段程式碼貼到DevTools的「主控台」裡面，然後隨意滾動滑鼠，看看印出的數值是多少，正常情況下應該要大於100
```js
document.body.addEventListener("wheel", (e) => {
    console.log(e.deltaY)
})
```
![image](https://github.com/hbl917070/Tiefsee4/assets/12185698/4354d8d2-d7cb-440a-ab83-fa2b79c22476)

**Comment by hbl917070** [comment]
阿，好像找到原因了
如果在 Windows 的設定裡面，把滑鼠的捲動行數設定成1或2，就會產生你說的 BUG

![image](https://github.com/hbl917070/Tiefsee4/assets/12185698/381cc7ad-79b0-466c-80b2-ded21af7b3f9)

**Comment by hcaynahs** [comment]
有用耶，把行數調高之後就都正常了！
謝謝你耐心幫我找到問題 : )
