### ISSUE TITLE
被 小紅傘 Avira 給封鎖了...

### ISSUE THREAD

**Issue by at3166** [hbl917070/Tiefsee4#44]
被 小紅傘 Avira 給封鎖了...

![螢幕擷取畫面 2024-06-15 150024](https://github.com/hbl917070/Tiefsee4/assets/1852478/33b1ee45-60c1-427e-b71f-31f93ca08845)

![image](https://github.com/hbl917070/Tiefsee4/assets/1852478/1e97abd8-fe6a-4b2f-9cd2-dfa9f3f392df)

**Comment by hbl917070** [comment]
這個我真的無能為力
這防毒完全就是亂槍打鳥，只要是他不認識的程式，然後沒辦法反編譯，就直接說是病毒
他說有問題的那個東西程式碼就這幾行而已，4.2.3版已經連上網功能都移除了，真的沒辦法再減少任何程式碼
https://github.com/hbl917070/Tiefsee4/blob/master/TiefseeLauncher/Program.cs

**Comment by at3166** [comment]
好喔, 關掉防毒, 加入 排除名單 解決😁
