### ISSUE TITLE
圖片資訊的中文路徑亂碼

### ISSUE THREAD

**Issue by bisechen** [hbl917070/Tiefsee4#5]
嗨，您好。

感謝你創作這個快速好用的看圖軟體，我正在使用當中。

不過我發現圖片資訊的中文路徑顯示為亂碼，請看下方的截圖 URL 。

https://imgur.com/wV4DrhK

**Comment by hbl917070** [comment]
方便提供該檔案讓我進行測試嗎

**Comment by bisechen** [comment]
> 方便提供該檔案讓我進行測試嗎
我檔案不方便公開，我以電子郵件傳給你。

**Comment by bisechen** [comment]
我剛剛用其它看圖軟體打開，這個檔案資訊的路徑也是顯示亂碼。這應該與 Tiefsee4 無關，不好意思給你添麻煩了。

**Comment by hbl917070** [comment]
你提供的圖片是 png，他把資訊儲存於「PNG-tEXt」裡面，這個欄位使用的編碼是 ISO-8859-1 ，所以才會不支援中文
如果希望 png 的附加資訊可以儲存中文，應該是要儲存在「PNG-iTXt」裡面，這個用的是 UTF-8 編碼
