### ISSUE TITLE
zooming 

### ISSUE THREAD

**Issue by tazztone** [hbl917070/Tiefsee4#53]
hey i installed tiefsee via microsoft store.
it worked well but since a few days ago i noticed zooming in via mouse is broken:
https://github.com/user-attachments/assets/0ceb24fd-1fcb-4e77-97d4-cda2a4b46043
you can see there is an invisible panel at the bottom blocking the view. and as we zoom in it gets bigger and bigger eventually hiding the entire image.
if you need more infos about my settings etc let me know.

**Comment by hbl917070** [comment]
After the browser automatically updated, the mechanism of CSS `zoom` works differently than before, which caused this bug. I am currently working on fixing this issue.

**Comment by tazztone** [comment]
works again. thanks a million!
