### ISSUE TITLE
Unable to view/無法正常查看圖像

### ISSUE THREAD

**Issue by sojuo** [hbl917070/Tiefsee4#54]
Can't view [one of my images](https://github.com/user-attachments/files/16824779/ResizedImage_2024-08-31_20-44-08_1.zip) in Tiefsee, but can view it in [Aves](https://github.com/user-attachments/files/16824779/ResizedImage_2024-08-31_20-44-08_1.zip) and [ImageGlass](https://imageglass.org/).
無法在Tiefsee中查看我的[一張圖像](https://github.com/user-attachments/files/16824779/ResizedImage_2024-08-31_20-44-08_1.zip)，但能在[Aves](https://github.com/user-attachments/files/16824779/ResizedImage_2024-08-31_20-44-08_1.zip)和[ImageGlass](https://imageglass.org/)中查看這張圖像。

**Comment by hbl917070** [comment]
My tests here are normal. 
Could you provide more information, such as the operating system version, Tiefsee version, and the actions you performed?

![image](https://github.com/user-attachments/assets/77e5293f-5861-404a-b593-ae6885ef5919)
