### ISSUE TITLE
建議增加 Reload 的功能

### ISSUE THREAD

**Issue by bisechen** [hbl917070/Tiefsee4#6]
Tiefsee4 在打開目錄裡面的圖檔之後，接著在該目錄新增圖檔時，新圖檔就無法打開來顯示。

簡易新增RELOAD的功能～^^

**Comment by hbl917070** [comment]
確實是需要這樣的功能
有在評估設計成：自動偵測檔案跟資料夾是否發生變化，有變化就顯示視窗詢問是否重新載入

目前的話，可以用快速拖曳重新載入同一張圖片
這相當於把圖片拉進Tiefsee裡面開啟，所以會觸發檔案列表更新
![](https://user-images.githubusercontent.com/12185698/237188265-9629adae-d183-444f-a3e1-78c25c2bf2ce.gif)

**Comment by bisechen** [comment]
我不太懂，為何這需要詢問是否重新載入呢？

**Comment by hbl917070** [comment]
初估判斷，可能有性能問題
例如：
在某一個資料夾裡面有10萬張圖片，並且有另一個程式固定每1秒會產生一個新的圖片在這個資料夾
如果使用者在 Tiefsee 裡面選擇的排序方式是用時間而非檔名，那麼光是檔案列表的排序可能就需要2秒以上的運算時間
在這樣的情況下，設計成全自動重新載入，必然會是個災難

至於實際情況是否真的會這樣，我要測試過才知道
目前還在處理其他部分

**Comment by bisechen** [comment]
原來如此，
這樣的話或許可以把這作成一個選項，
由使用者自己決定是否要啟用自動RELOAD，
當然也可以在此選項加上注意事項警語。

畢竟每新增一個圖檔就要問一次也是會很煩的～^^

不過我只知道UI裡面可以這樣做，但程式設計我不行～XD

**Comment by hbl917070** [comment]
4.1.2 加入自動偵測檔案變化的功能

當資料夾內的檔案發生變化(新增檔案、刪除檔案、重新命名)，會自動同步到 Tiefsee 的 檔案預覽面板
![GIF 2023-7-13 下午 09-56-38](https://github.com/hbl917070/Tiefsee4/assets/12185698/2dc9aec4-1140-4f86-a6e7-c517124c4645)

如果檔案列表同步上出了問題或是需要重新排序，檔案預覽面板 的右鍵選單裡面有一個「重新載入」
![2023-07-13 23-50-32](https://github.com/hbl917070/Tiefsee4/assets/12185698/1f9b3620-a7bf-480b-b480-21a66325c1ad)
