### ISSUE TITLE
佈局設定裡面的大型選擇按鈕問題

### ISSUE THREAD

**Issue by shaurnea** [hbl917070/Tiefsee4#8]
我已經把佈局設定裡面的大型選擇按鈕改成不顯示
![2023-06-17_200227](https://github.com/hbl917070/Tiefsee4/assets/136900427/70f06bc8-835d-412c-9c77-a503a7ebfd3d)

但大量瀏覽模式下還是強制顯示每百張的分段按鈕，因為100P和101P是連續圖，這樣圖檔就被切開了
![2023-06-17_200333](https://github.com/hbl917070/Tiefsee4/assets/136900427/442c7cdf-ad1a-4aec-9647-66491545e93d)

**Comment by hbl917070** [comment]
這個設定指的是一般圖片模式的按鈕，而不是大量瀏覽模式的按鈕

目前尚沒有找到適合的設計模式可以讓大量瀏覽模式直接載入所有圖片而不需要換頁

我看過的設計模式有幾種
1. 直接把資料夾所有圖片載入：只要資料夾的圖片一多，程式就會當掉
2. 載入時讀取所有圖片的size，然後只渲染當前畫面看得到的區域：這算是`1`的進階版，但對於有幾萬張圖片的資料夾來說還是照樣當掉
3. 設計成無限滾動，直接指定圖片的高度：這種模式顯然不適合用於看漫畫
4. 設計成無限滾動，捲動到最下面後就載入新的圖片：這種方式會讓右邊的滾動條失去作用，因為整體的高度會隨著載入的圖片的數量改變

是否有其他想法，或是在其他地方看過更好的設計模式呢

**Comment by shaurnea** [comment]
之前用的舊版3.0.2是每40張就分段，現在4.1.1版是每100張才分段，其實已經不錯了
成人向的條漫除了toomics平台的作品外幾乎沒有單話超過百張的，所以看這類的沒什麼問題
不過一般向的條漫沒有特地用合併圖片處理的話，幾乎都超過百張，就會發生我貼圖那情況
有辦法弄出可以自行設定要每幾張才出現分段的功能嗎？ 如果不行的話就算了，因為還有很多應變方法

還有種方法是把分段的張數提高，例如3.0.2版是40張，4.1.1版是100張
我看過單話數最多張圖的條漫也就快300張，且多數都在200以下
但如果這種改動會造成其他人使用上的困擾就不用了

**Comment by hbl917070** [comment]
增加每頁圖片的數量是很簡單的事情
但我沒辦法保證超過100張程式不會跑到當機
像是gif、apng、webp之類的動態圖，就會非常消耗資源
某些使用者的螢幕的解析度非常高，可能是4k甚至8k螢幕，這種情況下就算顯示的是靜態圖片也會是極大的負擔

我再評估看看在設定裡面讓使用者自訂每頁顯示的圖片數量的做法是否可行吧
就算超過100張真的不行，也應該要有減少數量的設定才合理，一些性能較差的電腦可能連100張都會跑到程式當機

**Comment by shaurnea** [comment]
可能我使用上都是JPG靜態圖居多(且最高解析度不超過2K)，沒有在你上述的情況下使用過，因此從沒發生過當機的情況。
且加載幾百張也是一瞬間的事情，完全沒有卡頓的感覺。個人的電腦配置是用很久的E3-1230V2+RX470

如果增加每頁圖片或讓使用者自訂每頁顯示的圖片數量很簡單且不怎麼花時間的話
可以出個特別版給專門看條漫的人使用(主要是避免因分段把連續圖切割開來的情況)
條漫一般都是720寬居多，最多就是1280寬，不會有4K 8K靜態圖的這種情況
就算是兩三百張應該也是秒加載吧？(目前百張是秒加載，再上去軟體沒更新前無法測試)
真的不行也沒關係，我目前應變方法是分成複數個資料夾來避免被大型選擇按鈕切割開
因為用合併圖片的方式處理的話一定會動到原圖，我覺得分成複數個資料夾會比較好。

![2023-06-18_124843](https://github.com/hbl917070/Tiefsee4/assets/136900427/25c1c50c-8801-4f19-b3cb-e3ea5ccb8901)

**Comment by hbl917070** [comment]
Tiefsee  4.1.2 
新增 自訂選項「大量瀏覽模式一頁顯示的圖片數量」
![image](https://github.com/hbl917070/Tiefsee4/assets/12185698/3696c8f4-9669-4447-ae38-2325e215d50f)
